CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID      VARCHAR2(10) PRIMARY KEY,
    EMPLOYEE_NAME    VARCHAR2(120),
    CTC              NUMBER(10,2),
    CTCPHR           NUMBER(10,2)
);
CREATE TABLE PROJECT (
    PROJECT_ID  NUMBER PRIMARY KEY,
    PROJECT_NAME  VARCHAR2(200) NOT NULL UNIQUE,
    SOW_PH NUMBER(20,2)
);


CREATE TABLE TIMECARD (
    TIMECARD_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID         varchar2(10),
    EMPLOYEE_NAME       VARCHAR2(120),
    DAILY_DATE          DATE,
    TIME_WORKED         NUMBER(2),
    TIME_CARD_STATE     VARCHAR2(50),
    TASK_TYPE           VARCHAR2(50),
    PROJECT_NAME        VARCHAR2(120),

);